### ISSUE TITLE
When running partition experiments on DCOS, the overcouting log file won't be pushed to S3

### ISSUE THREAD

**Issue by vitorenesduarte** [lasp-lang/lasp#154]

**Comment by cmeiklejohn** [comment]
Can you explain precisely what this problem is?

**Comment by vitorenesduarte** [comment]
We're only pushing on log per node. The server has to push two if I remember correctly.

**Comment by cmeiklejohn** [comment]
Can you just modify the convergence structure accordingly for this?

**Comment by vitorenesduarte** [comment]
Yes, will do this today.

**Comment by vitorenesduarte** [comment]
Fixed in [unstable](https://github.com/lasp-lang/lasp/compare/2ae41cf65e45f4ee37b411f8f1a2a981d16b35cd...e999f141d08393ed2d0fbe4df6e9e717217dc79b).
