### ISSUE TITLE
Make sure each running app on DCOS has a unique id

### ISSUE THREAD

**Issue by vitorenesduarte** [lasp-lang/lasp#160]

**Comment by cmeiklejohn** [comment]
What specifically needs to be done here?

**Comment by vitorenesduarte** [comment]
A running app in marathon has an id like:
- lasp_client_$TIMESTAMP
- lasp_server_$TIMESTAMP

This $TIMESTAMP comes from the DCOS Runner.
If we have multiple runners, we might have collisions.

**Comment by cmeiklejohn** [comment]
Can't you just drop $MESOS_TASK_ID in there to make it unique?

**Comment by cmeiklejohn** [comment]
I guess that will be different between the server and client, because each is a different task.  Can't you use the TASK_ID of the runner itself?

**Comment by vitorenesduarte** [comment]
Yes. If we always use the DCOS Runner, that's okay.
If we try to start the tasks locally, that won't be available.
So, if, for example, `transmission.sh` detects that TASK_ID is not defined, it just creates something random?

**Comment by vitorenesduarte** [comment]
In sprinter, the TASK_ID from the runner won't be available right?
So we need another environment variable on Lasp for this.

**Comment by cmeiklejohn** [comment]
Can we close this or is this something that still needs to be done?  We seem to be getting on fine without it.

**Comment by vitorenesduarte** [comment]
I'm closing it then.
I did this 3cb8e866a79b6cc4df87f5552ee536cbcc95edc4 to reduce the probability of a collision.
