### ISSUE TITLE
Improve check for connectedness algorithm

### ISSUE THREAD

**Issue by vitorenesduarte** [lasp-lang/lasp#161]

**Comment by cmeiklejohn** [comment]
How precisely should this be improved?  Can you put more information in the issue?

**Comment by vitorenesduarte** [comment]
Instead of checking that every node is connected to every other node, I think we can:
- do a graph traversal (breath first e.g.) and
- if we visit all nodes and
- all the links were bidirectional (this requirement comes from symmetric views from HyParView, right?) then
- the graph is connected

With 512 clients, using `get_path` instead of `get_shortest_path`, still takes 3 min.
