### ISSUE TITLE
Why use included applications for plumtree and partisan

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/lasp#181]
Why are plumtree and partisan included as `included_applications`?

**Comment by cmeiklejohn** [comment]
This was done because we need their supervisor running under Lasp's supervisor, to ensure that connections and related processes are started correctly and things are properly configured.

**Comment by tsloughter** [comment]
Hm, ok. It is just worrisome when I see it used since they can have unintended consequences and are often used when it could be better to change the dependency (for either easier configuration or removing `{mod, ...}` from it to make it not start anything) or set as `load` in the release.

**Comment by tsloughter** [comment]
I'll close this for now, but as I'm digging into the code I may have suggestions to improve on it.

**Comment by cmeiklejohn** [comment]
We welcome any suggestions you may have!
