### ISSUE TITLE
make lasp on CentOS 7, Erlang 20: gen_fsm:send_event/2 is deprecated

### ISSUE THREAD

**Issue by matthewwiese** [lasp-lang/lasp#239]
Just this afternoon I was setting up Lasp on a spare CentOS box to tinker with, and after cloning the *lasp* repo and attempting to `make`, I was greeted with the following error:
```
/home/matt/lasp/rebar3 compile
===> Verifying dependencies
===> Compiling lasp
===> Compiling src/lasp_core.erl failed
src/lasp_core.erl:916: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/lasp_core.erl:939: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/lasp_core.erl:956: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1

make: *** [compile] Error 1
```

I hopped into vim and changed the aforementioned lines to use `gen_statem:cast` and the issue was resolved. I assume this problem is because I'm using Erlang version 20 (and not due to anything CentOS related).

If so, I could submit a pull request, but I'm wary of doing so at the moment because I don't want to break anything for people using an older Erlang.

**Comment by tsloughter** [comment]
@matthewwiese use the `unstable` branch.

**Comment by matthewwiese** [comment]
@tsloughter Good suggestion, that does solve my problem.

However, on both `master` and `unstable` branches, running `make check` gives the same error: 
```
===> Compiling _build/test/lib/lasp/test/lasp_peer_to_peer_throughput_SUITE.erl failed
_build/test/lib/lasp/test/lasp_peer_to_peer_throughput_SUITE.erl:34: export_all flag enabled - all functions will be exported

make: *** [ct] Error 1
```

Not sure if that is at all related?

**Comment by cmeiklejohn** [comment]
We should modify that file to only export the required functions.  @matthewwiese want to fix that and send a pull request to unstable?

**Comment by cmeiklejohn** [comment]
Just compiled on Erlang 20 and didn't run into any issues.  Please re-open if these issue remain.
