### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by thdxr** [lasp-lang/lasp#245]
Hi I'm attempting to use Lasp inside an Elixir application however there's a ton of log spam.  How do I disable this?

**Comment by cmeiklejohn** [comment]
Good question -- I think a lot of it can be disabled by changing the settings used by lasp_logger, but that's still going to incur the penalty of dispatching to lager -- which, as we determined, can be significant.  Maybe we should try to parametrize it at compile time.

Hop into the Lasp slack, if you'd like, we'd love to know what you're doing and how we can help!

**Comment by thdxr** [comment]
Thanks for the response.  What's the slack information? Couldn't find it on the docs site

**Comment by cmeiklejohn** [comment]
Send me your email and I'll send you an invitation to the Slack: `christopher.meiklejohn@gmail.com`

**Comment by cmeiklejohn** [comment]
Most of the noisy messages have been switched to `lager:debug` or `lasp_logger:extended`.

**Comment by cmeiklejohn** [comment]
Re-open if you have more issues.
