### ISSUE TITLE
lasp membership undefined

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/lasp#251]
Investigating the issue of `enforce_once` crashing I discovered that the membership returned by partisan and lasp do not agree:

```
(nucleus@10.12.1.106)2> partisan_peer_service:members().
{ok,['nucleus@10.12.1.106','nucleus@10.12.1.105']}
(nucleus@10.12.1.106)3> lasp:query({<<"_membership">>, lwwregister}).
{ok,undefined}
```

This is why `enforce_once` will have `undefined` (or now the empty list `[]`) as the membership list it tries to sort.

Let me know what else I can dig up to help solve this.

**Comment by cmeiklejohn** [comment]
For one to get membership, one must enable the feature in the configuration.  :)
