### ISSUE TITLE
upgrade to latest gen_flow

### ISSUE THREAD

**Issue by evanmcc** [lasp-lang/lasp#253]
The version that lasp is currently using doesn't contain https://github.com/lasp-lang/gen_flow/pull/8, and has slowly-growing message queues while running that are never cleaned up.

**Comment by cmeiklejohn** [comment]
As far as I can tell, lasp master is using the latest gen_flow on hex.  Does the package need updating?  cc: @tsloughter has the control to do that only, I think.

**Comment by tsloughter** [comment]
I feel like there was another recent mention of me regarding making some releases. 

@cmeiklejohn do you know what I need to cut releases for? I can do it today.

**Comment by cmeiklejohn** [comment]
@tsloughter I think we need lasp_pg, gen_flow, partisan, and lasp.
