### ISSUE TITLE
Can't use in an Elixir mix project

### ISSUE THREAD

**Issue by cs-victor-nascimento** [lasp-lang/lasp#256]
Hello!

I was trying to give lasp a try but couldn't boot it in an Elixir project.

*When I include it in deps*:

```elixir
  defp deps do
    [
      {:lasp, "~> 0.3"} # last published version
    ]
  end
```

*Then `mix do deps.get, compile`*:

```
Error evaluating Rebar config script ./rebar.config.script:19: evaluation failed with reason error:{badmatch,[{erl_opts,[debug_info]},{profiles,[{docs,[{deps,[{edown,{git,[104,116,116,112,115,58,47,47,103,105,116,104,117,98,46,99,111,109,47,117,119,105,103,101,114,47,101,100,111,119,110,46,103,105,116],{tag,[48,46,56]}}}]},{edoc_opts,[{doclet,edown_doclet},{packages,false},{subpackages,true},{top_level_readme,{[46,47,82,69,65,68,77,69,46,109,100],[104,116,116,112,58,47,47,103,105,116,104,117,98,46,99,111,109,47,117,119,105,103,101,114,47,115,101,120,116]}}]}]}]},{deps,[{edown,[46,42],{git,[103,105,116,58,47,47,103,105,116,104,117,98,46,99,111,109,47,117,119,105,103,101,114,47,101,100,111,119,110,46,103,105,116],[72,69,65,68]}}]},{src_dirs,[[101,120,97,109,112,108,101,115]]},{edoc_opts,[{doclet,edown_doclet},{src_path,[[115,114,99,47],[101,120,97,109,112,108,101,115,47]]},{app_default,[104,116,116,112,58,47,47,119,119,119,46,101,114,108,97,110,103,46,111,114,103,47,100,111,99,47,109,97,110]},{top_level_readme,{[46,47,82,69,65,68,77,69,46,109,100],[104,116,116,112,58,47,47,103,105,116,104,117,98,46,99,111,109,47,117,119,105,103,101,114,47,115,101,120,116]}}]}]} and stacktrace [{erl_eval,expr,3,[]}]
Any dependencies defined in the script won't be available unless you add them to your Mix project
```

*Environment*:

- Elixir 1.5.2
- Erlang 20.0

Thanks!

**Comment by cmeiklejohn** [comment]
@tsloughter any thoughts here?

**Comment by cmeiklejohn** [comment]
One thing: I'm not sure Lasp runs under Erlang 20 just yet.  I'm not sure if that's related to the problem yet, but ideally you want to run with something on the 19 branch for now.

**Comment by cs-victor-nascimento** [comment]
Will try with OTP 19. I've seen the recent commit removing OTP 20 but I thought that was only because of execution time in Travis or something like it. The documentation also does not mention it (or I haven't seen it).

In any case, it would be greatly appreciated if we could have an Elixir example. THanks once again for your work!

**Comment by tsloughter** [comment]
We use it on OTP 20. Not sure what is going on in that crash. Is it for sure using rebar3 from mix to build, instead of rebar 2?

**Comment by cmeiklejohn** [comment]
Can you report the version of rebar that is being used for the build so we can try to get to the bottom of where the crash is happening?

**Comment by cs-victor-nascimento** [comment]
It is a rebar issue but not exactly a version issue. Mix has installed both versions of rebar. It seems it is not reading `rebar.config.script` properly from the `sext` repo.

I can reproduce the same error by depending only on sext. I will try to report this upstream. Thanks :)

**Comment by cmeiklejohn** [comment]
Thanks!

**Comment by cs-victor-nascimento** [comment]
After raising an issue in the sext repository, it is now fixed there. I can compile it with `1.4.1` now and `manager: :rebar` plus edown dependency.

Will try overriding Lasp's version to see if I can bootstrap it locally.

Thanks once again!

**Comment by cmeiklejohn** [comment]
I'm curious if Lasp even needs the sext dependency at this point.

**Comment by cmeiklejohn** [comment]
https://github.com/lasp-lang/lasp/pull/257

**Comment by cs-victor-nascimento** [comment]
My successful configuration deps is:

```elixir
      {:sext, "~> 1.4", manager: :rebar, override: true},
      {:edown, "~> 0.8"},
      {:lasp, "~> 0.3"}
```

**Comment by cmeiklejohn** [comment]
#257 merged, removes dependency on sext.
