### ISSUE TITLE
Allow to force gossip to syncrhonize

### ISSUE THREAD

**Issue by fbergero** [lasp-lang/lasp#264]
In some cases it is helpful to force the gossip protocol to issue an update to the other nodes.
For example after updating a CRDT variable one could ask LASP to start the gossip immediately disregard of what the gossip frequency is.

**Comment by cmeiklejohn** [comment]
Thoughts on https://github.com/lasp-lang/lasp/pull/265

**Comment by cmeiklejohn** [comment]
I'll close this issue and we can have the discussion in the PR thread.
