### ISSUE TITLE
Erlang 21 incompatible

### ISSUE THREAD

**Issue by fire** [lasp-lang/lasp#300]
Can't use erlang 21. One error is that Partisan complains about net_kernel:connect doesn't exist.

**Comment by Laymer** [comment]
@fire I do not know if that is a good idea nor wether @cmeiklejohn would approve this workaround but I am required to use Erlang/OTP 21 so the simplest way for me to do it was to add `partisan 3.0.0` and `lasp 0.9.0` as top level dependencies in my project. 

As of OTP 21 the `net_kernel:connect/1` function has been removed in favor of `connect_node/1`, but in my case this had no impact on the program behavior. So again, unless recommended by @cmeiklejohn I wouldn't rely on this tweak, but it seems to do the job for me so just letting you know in case it might help 🙂

**Comment by dischoen** [comment]
I ran into the same problem and switched back to 20.3, with a _make clean_ in between.
Then I had issues with incompatible .beam files from the previous build.
Maybe add the _-a_ flag to rebar3 clean?

apart from that, I am looking forward to lisp within erl!

**Comment by cmeiklejohn** [comment]
I haven't had time to port Lasp to the latest Partisan yet -- it's not really something I can get to in the next few weeks.  That said, that should be really the only thing preventing it from going to OTP 21.  I'd love it if someone else could send over a PR for this.
